### ISSUE TITLE
SafeguardA2AContext: getRetrievableAccounts throws NullPointerException when API key is null

### ISSUE THREAD

**Issue by msawberger** [OneIdentity/SafeguardJava#117]
Line 135: `account.setApiKey(retrieval.getApiKey().toCharArray());`
If the api key is not included in the response the toCharArray will cause a null pointer exception to occur.

**Comment by bnicholesdell** [comment]
This is actually an issue with SPP 7.1. SPP should always return an API key.  This bug has been fixed in SPP 7.2.  A workaround for this bug will also be included in the next release of SafeguardJava to allow the call to succeed even without the API key.

**Comment by bnicholesdell** [comment]
Add null check for api key.  https://github.com/OneIdentity/SafeguardJava/pull/118
