### ISSUE TITLE
Security Vulnerabilities on safeguardjava 7.3

### ISSUE THREAD

**Issue by EHoward99** [OneIdentity/SafeguardJava#131]
Our change oversight team detected the following vulnerabilities on safeguardjava 7.3.0.210014.  Can One Identity provide a response regarding severity?  Thanks
Threat 10  Security-Critical                     org.springframework:spring-web:5.3.29
Threat 8    Security-High                         com.squareup.okio:okio:3.3.0
Threat 8    Security-High                         org.apache.velocity:velocity:1.6.2
Threat 7    License-Threat Not Assigned  ognl:ognl:3.3.4
Threat 7    License-Threat Not Assigned  org.reactivestreams:reactive-streams:1.0.3
Thanks
EHoward

**Comment by bnicholesdell** [comment]
SafeguardJava is a java library and does not expose any of these packages publically.  We are preparing to release a 7.4 package and will be updating dependent packages at that time.

**Comment by bnicholesdell** [comment]
All packages have been updated in release 7.4.  Please upgrade to the latest version of SafeguardJava.
