### ISSUE TITLE
documentation err?

### ISSUE THREAD

**Issue by walkerpauldavid** [OneIdentity/SafeguardJava#18]
hi, the documentation examples show the use of a byte array whereas in fact a char array is required; the signature method of com.oneidentity.safeguard.safeguardjava.Safeguard.connect is using a char array not a byte array. The example connection code on Github shows the use of String.getBytes() rather than String.toCharArray()

char[] _p1 = _password.toCharArray();
        
![2019-09-05_09h27_59](https://user-images.githubusercontent.com/33701755/64325162-8fd03180-cfbf-11e9-853a-ab8a928b180d.png)

**Comment by bnicholesdell** [comment]
Thanks.  I just updated the readme.
