### ISSUE TITLE
Support certificate thumbprint to connect to Safeguard

### ISSUE THREAD

**Issue by rdopazo** [OneIdentity/SafeguardJava#53]
Hi all,
It would be great if Java SDK can support certificate thumbprint to connect to Safeguard instead of using certificate file and password, the same way we do with Powershell or .NET. 
It is much more easy for integrations to use the thumbprint than file plus passwords.
Regards,
Raul

**Comment by bnicholesdell** [comment]
Since SafeguardJava is meant to be a cross platform solution, adding the ability to use certificates by thumbprint would be a Windows Only feature.  The Powershell Cmdlets and SafeguardDotNet library are able to identify and pull certificates using a thumbprint, by taking advantage of the Windows certificate store.  That same certificate store doesn't exist on other platforms which is why a keystore file or PFX certificate must be provided when using SafeguardJava.  We can look into providing this functionality in SafeguardJava, but since it would be a Windows Only feature, in that case it would probably be better to just use the SafeguardDotNet library.

**Comment by rdopazo** [comment]
We are trying to integrate one RPA vendor with Safeguard, and they use Windows Servers for running automated process and Java to create the process logic (Java packages). If we want to perform a clean integration, and avoid users and passwords in the RPA credential manager, it is not a good approach to have to provide files and passwords in the RPA process logic. 
I mean, using keystore files or PFX with passwords we are forced to still use the RPA credential manager...so we don't remove the required security concern from it. I understand the logic behind your comments, and i know that thumbprint is only possible in Windows platforms, but in this case it will be really interesting to have it

**Comment by bnicholesdell** [comment]
The latest release 6.7.1.96999 includes new APIs for connecting to Safeguard using a thumbprint.  These APIs will only work on the Windows platform and it expects the certificates to be installed into the current user's personal store.

**Comment by vvarga** [comment]
@bnicholesdell I'm trying to connect to Safeguard using a certificate thumbprint but I get NullPointerException.
I have
`ISafeguardA2AContext a2a = new SafeguardA2AContext(appliance, certThumbprint, 3, true, new CertificateValidator());`
and I get
`java.lang.NullPointerException
	at com.oneidentity.safeguard.safeguardjava.data.CertificateContext.cloneObject(CertificateContext.java:87)
	at com.oneidentity.safeguard.safeguardjava.SafeguardA2AContext.<init>(SafeguardA2AContext.java:53)
	at com.oneidentity.safeguard.safeguardjava.SafeguardA2AContext.<init>(SafeguardA2AContext.java:65)
	at com.oneidentity.safeguard.automationanywhere.getPasswordOfAccount_thumbprint.getPasswordOfAccount(getPasswordOfAccount_thumbprint.java:30)`

Thanks for your help!
Viktor

**Comment by bnicholesdell** [comment]
The reason why you are seeing an exception is because thumbprints is not supported for SafeguardA2AContext().  That will need to be added.  Also, you shouldn't be calling new SafeguardA2AContext() directly.  Rather, you should call the static factory method Safeguard.A2A.getContext().  I need to do a better job of only exposing the interface classes which means that if you are using anything other than the Safeguard() static factory methods or the interface classes, your code may break in future releases.

**Comment by bnicholesdell** [comment]
I have added the support for certificate thumbprints to the A2a context and event listeners.  I created a build 6.7.3.101653-SNAPSHOT which you can find here https://github.com/OneIdentity/SafeguardJava/releases/download/release-6.7.3.101653-SNAPSHOT/safeguardjava-6.7.3.101653-SNAPSHOT.jar.  Give it a try.  If it works for you, I will push it to the maven central repository as a release.

**Comment by vvarga** [comment]
Thanks a lot Brad! Unfortunately it does not work yet. I used
`ISafeguardA2AContext a2a = Safeguard.A2A.getContext(appliance, certThumbprint, 3, true);
List<A2ARetrievableAccount> accounts = a2a.getRetrievableAccounts();`
but it failed with
`Error returned from Safeguard API, Error: 401 {"Code":60094,"Message":"Authorization is denied for this request.","InnerError":null}`
Within a2a I can see the certificateAlias is matching the certificate that is stored in the Personal certstore so I believe it could obtain the certificate by the thumbprint.

It is still working if I use the cert path+password based login using
`ISafeguardA2AContext a2a = Safeguard.A2A.getContext(appliance,certpath, certpassword, 3 ,true);`

**Comment by bnicholesdell** [comment]
This seems like a misconfiguration in your environment.  I have retested this in my environment and it all seems to work as expected.  The following is how I have my environment set up.  Let me know if you have something different:

1. I added a certificate user to SPP called javalibcertuser
2. Associated the certificate thumbprint with the javalibcertuser user
3. Added the associated certificate as a trusted certificate in SPP
4. Imported the associated certificate and private key into the Windows current user personal certificate store on the windows client.
5. Created an A2A registration called SafeguardJava
6. Associated the javalibcertuser user with the SafeguardJava A2A registration
7. Enabled Credential Retrieval and Visible to Certificate Users on the SafeguardJava registration
8. Added a retrievable account to the SafeguardJava registration

With that environment in place, I am able to connect via a2a, pull a password for the account and get the retrievable accounts.  If I were to guess on what might be wrong in your environment, it would be one of the following:

1. The certificate user certificate has not been added as a trusted certificate in SPP
2. The certificate user certificate and private key has not be stored in the Windows current user/Personal/certificates store on the Windows client. The certificate must be stored for the current user.  Storing it in the local machine/personal won't work.  This is a limitation of the windows certificate provider for java (SunMSAPI provider).

As part of the SafeguardJava github project, there is a client app under test/safeguardjavaclient that I use to test the functionality of various parts of SafeguardJava.  In the test app there are tests for verifying the A2A with windows certificate thumbprint functionality.  That is the code that I am using to verify that the A2A context is working.

**Comment by vvarga** [comment]
You were right, I found out that the certificate imported into the Personal store did not contain the private key. Deleting it then importing the proper PFX made it work.
Thanks a lot for your help Brad!
