### ISSUE TITLE
2 issues and suggested fixes (RestClient.java) in v6.7.0

### ISSUE THREAD

**Issue by robertlbyrne** [OneIdentity/SafeguardJava#73]
Hi, thanks for this very useful integration package!

For info, two issues I needed to fix to get v6.7.0 to work. Screenshots are the corrected code suggestions.

1) Query parameters not passed correctly in RestClient.prepareRequest()
This means you cannot ask for a credential other than type=Password.

![image](https://user-images.githubusercontent.com/19616275/98546503-17d25b00-2297-11eb-8a47-994385c198a8.png)

2) Wrong certificate alias used in RestClient.getClientWithCertificate()
This causes authorization to fail.

![image](https://user-images.githubusercontent.com/19616275/98548342-a8119f80-2299-11eb-9d3b-a13ce6ec5a36.png)

**Comment by bnicholesdell** [comment]
The first issue mentioned is definitely a bug.  I will get that one fixed.  The second issue has already been fixed in the latest code.  

`            SSLConnectionSocketFactory sslsf = null; 
            if (ignoreSsl) {
                sslsf = new SSLConnectionSocketFactory(getSSLContext(clientKs, keyPass, **certificateAlias == null ? aliases.get(0) : certificateAlias**, certificateContext), NoopHostnameVerifier.INSTANCE);
            } else if (validationCallback != null) {
                sslsf = new SSLConnectionSocketFactory(getSSLContext(clientKs, keyPass, certificateAlias == null ? aliases.get(0) : certificateAlias, certificateContext), validationCallback); 
            } else {
                sslsf = new SSLConnectionSocketFactory(getSSLContext(clientKs, keyPass, certificateAlias == null ? aliases.get(0) : certificateAlias, certificateContext));
            }
`
